create database MYDB;
use MYDB;

CREATE TABLE CUSTOMERS(
CUST_ID int AUTO_INCREMENT NOT NULL PRIMARY KEY,                                                  
CUST_FIRSTNAME VARchar(255)  NOT NULL,
CUST_LASTNAME VARCHAR(255) NOT NULL,
CUST_NICKNAME VARCHAR(255),
CUST_AGE int,
CUST_GENDER char(1) not null,
CUST_COUNTRY VARCHAR(255) not null,
CUST_SALARY decimal not null
);
DESCRIBE TABLE CUSTOMERS;